### ISSUE TITLE
有sql吗谢谢

### ISSUE THREAD

**Issue by czz1233** [MaShantao/JzyOABackend#1]
有sql吗谢谢

**Comment by MaShantao** [comment]
sql有的，我等会上传一下，不过你也可以根据数据库UML图直接创建就可以。

**Comment by czz1233** [comment]
我弄了一天 数据对不上
---原始邮件---
发件人:&quot;MaShantao&quot;<notifications@github.com&gt;
发送时间:2021年3月7日 星期日 下午3:44
收件人:&quot;MaShantao/JzyOABackend&quot;<JzyOABackend@noreply.github.com&gt;
抄送:&quot;奔跑的小乌龟&quot;<863335016@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;
主题:Re: [MaShantao/JzyOABackend] 有sql吗谢谢 (#1)



sql有的，我等会上传一下，不过你也可以根据数据库UML图直接创建就可以。

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by MaShantao** [comment]
我上传了一版数据库，抹掉了敏感信息，你先试试吧，应该是可以运行的。

**Comment by czz1233** [comment]
> 有sql吗谢谢
